# Generated by Django 4.2.3 on 2023-08-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
