# Generated by Django 4.2.3 on 2023-08-06 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Userdata', '0001_initial'),
        ('usercart', '0002_userproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userdata.userprofile'),
        ),
    ]
