# Generated by Django 4.2.3 on 2023-08-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercart', '0005_shoppingcartitem_remove_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='proimage',
            field=models.CharField(default='', max_length=100),
        ),
    ]
