# Generated by Django 5.0.1 on 2024-09-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercart', '0009_product_category_alter_product_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
