# Generated by Django 5.0.1 on 2024-09-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercart', '0011_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('dry_fruits', 'Dry Fruits'), ('flowers', 'Flowers')], default='vegetables', max_length=20),
        ),
    ]
